### PR TITLE
Correct lower case spelling of 'coin' in 'Emercoin'

### PR DESCRIPTION
**Pull request by vx28643**
Corrects lower case spelling of 'coin' in 'Emercoin', for consistency. It's confusing to have different spellings. Review changes and accept if helpful. No problem if you want to ignore. Thanks.

### CODE REVIEW

**Comment by EvgenijM86** [comment]
const string strMessageMagic = "Emercoin Signed Message:\n";

This would break message signing.

**Comment by vx28643** [comment]
Ok, reverted for strMessageMagic. let me know if there's others.

**Comment by EvgenijM86** [comment]
Yes, it seems everything is fine now. Can you send this pull request to https://github.com/Emercoin/emercoin/ ? This our official github development account.

**Comment by vx28643** [comment]
Thanks. I have made the same PR on the other repro.

**Pull request closed without merging**
